//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAExtract.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AAExtract.Translations.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string OutputDirectoryExists {
            get {
                return ResourceManager.GetString("OutputDirectoryExists", resourceCulture);
            }
        }
        
        internal static string ManifestFileDoesNotExist {
            get {
                return ResourceManager.GetString("ManifestFileDoesNotExist", resourceCulture);
            }
        }
        
        internal static string MainAssemblyBlobDoesNotExist {
            get {
                return ResourceManager.GetString("MainAssemblyBlobDoesNotExist", resourceCulture);
            }
        }
        
        internal static string IndexMissingException {
            get {
                return ResourceManager.GetString("IndexMissingException", resourceCulture);
            }
        }
        
        internal static string AssemblyNameCouldNotBeFound {
            get {
                return ResourceManager.GetString("AssemblyNameCouldNotBeFound", resourceCulture);
            }
        }
    }
}
